name: 'Acción de repetición con JavaScript'
author: 'Julen'
description: 'Repite un número de veces el texto indicado'

inputs:
  input_text:
    description: 'El texto que queremos repetir varias veces'
    required: true
  num_of_repeats:
    description: 'Número de veces que queremos que aparezca el texto'
    required: false
    default: '1'

outputs:
  output_text:
    description: 'El texto repetido el número de veces indicado'
  
runs:
  using: 'node12'
  main: 'src/main.js'

branding:
  icon: 'rotate-cw'
  color: 'yellow'
